"""Reusable provider-native OHLCV ingestion utilities for Empire stonks."""

from empire_stonks_ohlcv.config import EODDataCredentials, OHLCVConfig
from empire_stonks_ohlcv.eoddata import (
    EODDATA_CONTENT_TYPE,
    EODDATA_PROVIDER_CODE,
    EODDataHTTPResponse,
    EODDataHTTPTransport,
    acquire_eoddata_objects,
)
from empire_stonks_ohlcv.eoddata_symbols import (
    EODDataSymbolListParseResult,
    parse_eoddata_symbol_list,
)
from empire_stonks_ohlcv.eoddata_quotes import (
    EODDataQuoteListParseResult,
    parse_eoddata_quote_list,
)
from empire_stonks_ohlcv.eoddata_import import (
    EODDataImportResult,
    import_eoddata_daily,
)
from empire_stonks_ohlcv.eoddata_runner import (
    EODDATA_DAILY_JOB_NAME,
    EODDataDailyRunResult,
    run_eoddata_daily,
)
from empire_stonks_ohlcv.exceptions import (
    EmpireStonksOHLCVError,
    OHLCVAcquisitionError,
    OHLCVConfigError,
    OHLCVParseError,
    OHLCVPersistenceError,
    OHLCVWorkflowError,
)
from empire_stonks_ohlcv.import_boundary import execute_import_boundary
from empire_stonks_ohlcv.health import (
    ProviderMarketHealth,
    ProviderSeriesHealth,
    ProviderWeekdayGapResult,
    WeekdayGapCandidate,
    select_provider_market_health,
    select_provider_series_health,
    select_provider_weekday_gaps,
)
from empire_stonks_ohlcv.models import DailyBar, ProviderListing
from empire_stonks_ohlcv.object_store import (
    RAW_SOURCE_OBJECT_KIND,
    build_raw_filename,
    build_raw_object_key,
    store_raw_bytes,
    store_raw_file,
)
from empire_stonks_ohlcv.listings import (
    ProviderListingWriteResult,
    ResolvedProviderListing,
    upsert_provider_listings,
)
from empire_stonks_ohlcv.daily_bars import DailyBarWriteInput, upsert_daily_bars
from empire_stonks_ohlcv.queries import (
    DailyBarDateRange,
    ProviderListingCoverage,
    select_daily_bar_date_range,
    select_latest_trading_date,
    select_provider_latest_trading_date,
    select_provider_listing_coverage,
)
from empire_stonks_ohlcv.provider_contract import (
    AcquireProviderObjects,
    ParseProviderObjects,
)
from empire_stonks_ohlcv.reporting import (
    PDF_REPORT_OBJECT_KIND,
    REPORT_OBJECT_KIND,
    REPORT_SCHEMA_VERSION,
    build_eoddata_report,
    build_report_object_key,
    eoddata_report_to_json,
    store_eoddata_pdf_report,
    store_eoddata_report,
)
from empire_stonks_ohlcv.reports import (
    EODDATA_DAILY_PDF_REPORT_ID,
    render_eoddata_daily_pdf,
)
from empire_stonks_ohlcv.results import (
    AcquiredObject,
    ImportIssue,
    ParsedListingBatch,
    ParsedProviderOutput,
    PersistenceCounts,
    ProviderImportResult,
    ProviderSourceMetadata,
)
from empire_stonks_ohlcv.runner import (
    JOB_PROVIDER_CODES,
    SAFE_FAILURE_MESSAGE,
    OHLCVRunResult,
    build_run_summary,
    run_provider_import,
    run_provider_pipeline,
)
from empire_stonks_ohlcv.source_snapshots import (
    SourceSnapshotRegistration,
    upsert_provider_source_snapshot,
)
from empire_stonks_ohlcv.source_conventions import (
    EODDATA_DAILY_SOURCE,
    EODDATA_SYMBOL_LIST_SOURCE,
    STOOQ_DAILY_SOURCE,
    STOOQ_HISTORY_SOURCE,
    YAHOO_DAILY_SOURCE,
)
from empire_stonks_ohlcv.stooq_history import (
    STOOQ_HISTORY_ARCHIVE_NAME,
    STOOQ_HISTORY_CORE_ARCHIVE_NAME,
    STOOQ_HISTORY_HEADER,
    STOOQ_HISTORY_MARKETS,
    STOOQ_HISTORY_PROVIDER_CODE,
    StooqHistoryChunk,
    StooqHistoryDiscovery,
    StooqHistoryMarketParseCounts,
    StooqHistoryMember,
    StooqHistoryParseProgress,
    StooqHistoryParser,
    StooqHistoryParseSummary,
    StooqHistoryScope,
    inspect_stooq_history_archive,
)
from empire_stonks_ohlcv.stooq_history_runner import (
    STOOQ_HISTORY_HEARTBEAT_TIMEOUT_SECONDS,
    STOOQ_HISTORY_JOB_NAME,
    STOOQ_HISTORY_SUBJECT_KEY,
    StooqHistoryRunResult,
    run_stooq_history_backfill,
)
from empire_stonks_ohlcv.stooq_history_reporting import (
    STOOQ_HISTORY_REPORT_FILENAME,
    STOOQ_HISTORY_REPORT_LOGICAL_NAME,
    STOOQ_HISTORY_REPORT_TYPE,
    StooqHistoryCoverage,
    StooqHistoryMarketCoverage,
    StooqHistorySeriesCoverage,
    build_stooq_history_report,
    select_stooq_history_coverage,
    stooq_history_report_to_json,
    store_stooq_history_report,
)
from empire_stonks_ohlcv.stooq_history_writer import (
    StooqHistoryChunkWriteResult,
    StooqHistoryChunkWriter,
    StooqHistoryWriteSummary,
)
from empire_stonks_ohlcv.validation import (
    MAX_ISSUE_SAMPLES,
    BoundedIssueSummary,
    CrossFeedOutcomeCounts,
    FeedOutcomeCounts,
    ProviderValidationResult,
    RowRejectionSummary,
    SourceMarketWriteCounts,
)

__all__ = [
    "AcquiredObject",
    "AcquireProviderObjects",
    "BoundedIssueSummary",
    "CrossFeedOutcomeCounts",
    "DailyBarDateRange",
    "DailyBarWriteInput",
    "EODDATA_CONTENT_TYPE",
    "EODDATA_DAILY_SOURCE",
    "EODDATA_DAILY_JOB_NAME",
    "EODDATA_DAILY_PDF_REPORT_ID",
    "EODDATA_PROVIDER_CODE",
    "EODDATA_SYMBOL_LIST_SOURCE",
    "EODDataCredentials",
    "EODDataDailyRunResult",
    "EODDataHTTPResponse",
    "EODDataHTTPTransport",
    "EODDataImportResult",
    "EODDataQuoteListParseResult",
    "EODDataSymbolListParseResult",
    "FeedOutcomeCounts",
    "DailyBar",
    "EmpireStonksOHLCVError",
    "ImportIssue",
    "JOB_PROVIDER_CODES",
    "MAX_ISSUE_SAMPLES",
    "OHLCVAcquisitionError",
    "OHLCVConfig",
    "OHLCVConfigError",
    "OHLCVParseError",
    "OHLCVPersistenceError",
    "OHLCVWorkflowError",
    "OHLCVRunResult",
    "PDF_REPORT_OBJECT_KIND",
    "ParsedListingBatch",
    "ParsedProviderOutput",
    "ParseProviderObjects",
    "PersistenceCounts",
    "ProviderListing",
    "ProviderListingCoverage",
    "ProviderListingWriteResult",
    "ProviderMarketHealth",
    "ProviderImportResult",
    "ProviderSourceMetadata",
    "ProviderSeriesHealth",
    "ProviderValidationResult",
    "RowRejectionSummary",
    "ProviderWeekdayGapResult",
    "RAW_SOURCE_OBJECT_KIND",
    "REPORT_OBJECT_KIND",
    "REPORT_SCHEMA_VERSION",
    "ResolvedProviderListing",
    "SAFE_FAILURE_MESSAGE",
    "SourceSnapshotRegistration",
    "SourceMarketWriteCounts",
    "STOOQ_DAILY_SOURCE",
    "STOOQ_HISTORY_SOURCE",
    "STOOQ_HISTORY_ARCHIVE_NAME",
    "STOOQ_HISTORY_CORE_ARCHIVE_NAME",
    "STOOQ_HISTORY_HEADER",
    "STOOQ_HISTORY_HEARTBEAT_TIMEOUT_SECONDS",
    "STOOQ_HISTORY_JOB_NAME",
    "STOOQ_HISTORY_MARKETS",
    "STOOQ_HISTORY_PROVIDER_CODE",
    "STOOQ_HISTORY_REPORT_FILENAME",
    "STOOQ_HISTORY_REPORT_LOGICAL_NAME",
    "STOOQ_HISTORY_REPORT_TYPE",
    "STOOQ_HISTORY_SUBJECT_KEY",
    "StooqHistoryChunk",
    "StooqHistoryChunkWriteResult",
    "StooqHistoryChunkWriter",
    "StooqHistoryCoverage",
    "StooqHistoryDiscovery",
    "StooqHistoryMarketParseCounts",
    "StooqHistoryMarketCoverage",
    "StooqHistoryMember",
    "StooqHistoryParseProgress",
    "StooqHistoryParser",
    "StooqHistoryParseSummary",
    "StooqHistoryScope",
    "StooqHistoryRunResult",
    "StooqHistorySeriesCoverage",
    "StooqHistoryWriteSummary",
    "YAHOO_DAILY_SOURCE",
    "WeekdayGapCandidate",
    "acquire_eoddata_objects",
    "build_raw_filename",
    "build_raw_object_key",
    "build_eoddata_report",
    "build_report_object_key",
    "build_stooq_history_report",
    "eoddata_report_to_json",
    "build_run_summary",
    "execute_import_boundary",
    "import_eoddata_daily",
    "inspect_stooq_history_archive",
    "parse_eoddata_quote_list",
    "parse_eoddata_symbol_list",
    "upsert_provider_listings",
    "upsert_daily_bars",
    "upsert_provider_source_snapshot",
    "select_daily_bar_date_range",
    "select_latest_trading_date",
    "select_provider_latest_trading_date",
    "select_provider_listing_coverage",
    "select_provider_market_health",
    "select_provider_series_health",
    "select_provider_weekday_gaps",
    "select_stooq_history_coverage",
    "run_provider_import",
    "run_provider_pipeline",
    "run_eoddata_daily",
    "run_stooq_history_backfill",
    "render_eoddata_daily_pdf",
    "store_raw_bytes",
    "stooq_history_report_to_json",
    "store_eoddata_report",
    "store_eoddata_pdf_report",
    "store_raw_file",
    "store_stooq_history_report",
]
