import json
import subprocess
import sys

import pytest

import empire_stonks_tech_indicators as public_api
from empire_stonks_tech_indicators import exceptions as exceptions_module
from empire_stonks_tech_indicators.exceptions import (
    EmpireStonksTechIndicatorsError,
    TechIndicatorsCalculationError,
    TechIndicatorsConfigError,
    TechIndicatorsPersistenceError,
    TechIndicatorsValidationError,
    TechIndicatorsWriterLockLostError,
    TechIndicatorsWorkflowError,
)


PUBLIC_EXCEPTIONS = (
    EmpireStonksTechIndicatorsError,
    TechIndicatorsCalculationError,
    TechIndicatorsConfigError,
    TechIndicatorsPersistenceError,
    TechIndicatorsValidationError,
    TechIndicatorsWorkflowError,
    TechIndicatorsWriterLockLostError,
)


def test_public_api_is_explicit() -> None:
    expected = [exception.__name__ for exception in PUBLIC_EXCEPTIONS]

    assert public_api.__all__ == [
        *expected,
        "BenchmarkConfig",
        "TechIndicatorsConfig",
        "TECH_INDICATORS_CORE_DOMAIN",
        "TECH_INDICATORS_DEFAULT_SUBJECT_KEY",
        "TECH_INDICATORS_HEARTBEAT_TIMEOUT_SECONDS",
        "TECH_INDICATORS_SAFE_FAILURE_MESSAGE",
        "TechIndicatorsCoreRun",
        "build_tech_indicators_core_summary",
        "TECH_INDICATORS_LOCK_CONTENDED_MESSAGE",
        "TECH_INDICATORS_LOCK_FAILURE_MESSAGE",
        "TECH_INDICATORS_LOCK_LOST_MESSAGE",
        "TECH_INDICATORS_TEMPORARY_FAILURE_EXIT_CODE",
        "TechIndicatorsWriterLock",
        "WriterLockAcquisition",
        "WriterLockOutcome",
        "acquire_tech_indicators_writer_lock",
        "TECH_INDICATORS_SCOPED_SUBJECT_PREFIX",
        "TECH_INDICATORS_SCOPE_SCHEMA_VERSION",
        "BACKFILL_CONFIRMATION_MAX_LISTINGS",
        "BACKFILL_CONFIRMATION_MAX_SOURCE_ROWS",
        "ResolvedTechIndicatorsBackfillScope",
        "TechIndicatorsBackfillCursor",
        "TechIndicatorsBackfillScope",
        "resolve_tech_indicators_backfill_scope",
        "ResolvedTechIndicatorsDailyScope",
        "TechIndicatorsDailyScope",
        "resolve_tech_indicators_daily_scope",
        "TechIndicatorsDailyRunResult",
        "run_tech_indicators_daily",
        "TechIndicatorsBackfillRunResult",
        "run_tech_indicators_backfill",
        "AlignedReturnArrays",
        "BarStructureArrays",
        "BollingerStateArrays",
        "CalculationArrays",
        "DirectionalMovementArrays",
        "MaskedFloatArray",
        "RangeRelationshipArrays",
        "ReturnArrays",
        "ReturnStatisticArrays",
        "RsiAtrArrays",
        "BenchmarkHistory",
        "EligibleListing",
        "EODDATA_DAILY_JOB_NAME",
        "ListingStateComparison",
        "MacdArrays",
        "MovingAverageArrays",
        "MovingAverageTrendArrays",
        "SourceReadinessDecision",
        "SpxBetaArrays",
        "SpxCorrelationArrays",
        "SpxFeatureArrays",
        "SpxPriceRatioArrays",
        "SpxRelativeReturnArrays",
        "StreakArrays",
        "TALibAdapter",
        "TALibRuntimeInfo",
        "VolumeLiquidityArrays",
        "YAHOO_DAILY_JOB_NAME",
        "AffectedRange",
        "AffectedRangePlan",
        "AffectedRangeReason",
        "PUBLISHED_MODEL_INPUT_FIELDS",
        "PUBLISHED_RANKING_FIELDS",
        "PublishedFeatureCoverage",
        "PublishedFeatureFreshness",
        "PublishedFeatureRankingRow",
        "PublishedModelInputRow",
        "PublishedModelInputSnapshot",
        "PublishedReadinessToken",
        "REPORT_FEATURE_FIELDS",
        "ReportBenchmarkCoverage",
        "ReportDatabaseSummary",
        "ReportDateCoverage",
        "ReportDimensionCoverage",
        "ReportFeatureCoverage",
        "ReportVersionCoverage",
        "BACKFILL_JSON_REPORT_LOGICAL_NAME",
        "BACKFILL_PDF_REPORT_LOGICAL_NAME",
        "DAILY_JSON_REPORT_LOGICAL_NAME",
        "DAILY_PDF_REPORT_LOGICAL_NAME",
        "DEFAULT_REPORT_STORAGE_ROOT",
        "JSON_REPORT_CONTENT_TYPE",
        "JSON_REPORT_FILENAME",
        "JSON_REPORT_LOGICAL_NAMES",
        "JSON_REPORT_OBJECT_KIND",
        "PDF_REPORT_CONTENT_TYPE",
        "PDF_REPORT_FILENAME",
        "PDF_REPORT_LOGICAL_NAMES",
        "PDF_REPORT_OBJECT_KIND",
        "build_tech_indicators_report_object_key",
        "store_tech_indicators_json_report",
        "store_tech_indicators_pdf_report",
        "tech_indicators_report_metadata",
        "PDF_DIAGNOSTIC_SAMPLE_LIMIT",
        "PDF_FEATURE_EXCEPTION_LIMIT",
        "PDF_LISTING_SAMPLE_LIMIT",
        "PDF_MAXIMUM_BYTES",
        "PDF_MAXIMUM_PAGES",
        "PdfFeatureFamilyCoverage",
        "TECH_INDICATORS_PDF_FEATURE_FAMILIES",
        "render_tech_indicators_report_pdf",
        "roll_up_pdf_feature_coverage",
        "BACKFILL_CORE_JOB_NAME",
        "BACKFILL_REPORT_ID",
        "BENCHMARK_CONTRACT_VERSION",
        "DAILY_CORE_JOB_NAME",
        "DAILY_REPORT_ID",
        "NATIVE_VALUE_NOTE_MESSAGES",
        "NATIVE_VALUE_NOTE_ORDER",
        "PUBLICATION_READINESS_REASON_CODES",
        "REPORT_DIAGNOSTIC_MESSAGE_CATALOG",
        "REPORT_DIAGNOSTIC_SAMPLE_LIMIT",
        "REPORT_MAXIMUM_BYTES",
        "REPORT_MESSAGE_CATALOG",
        "REPORT_PHASE_ORDER",
        "REPORT_SCHEMA_VERSION",
        "SOURCE_READINESS_REASON_CODES",
        "LockOutcome",
        "PublicationMethod",
        "PublicationReadiness",
        "PublicationReportPhase",
        "ReportBackfill",
        "ReportCounts",
        "ReportCoverage",
        "ReportCursor",
        "ReportDatabasePerformance",
        "ReportDiagnosticSample",
        "ReportDimensionCount",
        "ReportIdentity",
        "ReportIssueAggregate",
        "ReportLock",
        "ReportNativeValueSemantics",
        "ReportOutcome",
        "ReportPerformance",
        "ReportPhaseTiming",
        "ReportProviderEvidence",
        "ReportPublication",
        "ReportReasonCount",
        "ReportScope",
        "ReportSourceBenchmark",
        "ReportSourceReadiness",
        "ReportThroughput",
        "ReportVersions",
        "ReportWrites",
        "SourceReadinessStatus",
        "TechIndicatorsReport",
        "WorkflowKind",
        "make_report_diagnostic_samples",
        "render_tech_indicators_report_json",
        "assemble_feature_rows",
        "calculate_aligned_returns",
        "calculate_spx_beta",
        "calculate_spx_correlation",
        "calculate_spx_features",
        "calculate_spx_price_ratios",
        "calculate_spx_relative_returns",
        "calculate_bar_structure",
        "calculate_bollinger_state",
        "calculate_directional_movement",
        "calculate_macd",
        "calculate_moving_averages",
        "calculate_moving_average_trends",
        "calculate_range_relationships",
        "calculate_return_statistics",
        "calculate_returns",
        "calculate_rsi_atr",
        "calculate_streaks",
        "calculate_volume_liquidity",
        "decide_source_readiness",
        "iter_source_bar_pages",
        "is_spx_supported_subject",
        "iter_state_comparison_pages",
        "load_spx_benchmark_history",
        "normalize_source_bars",
        "plan_affected_ranges",
        "resolve_spx_benchmark",
        "read_published_model_inputs",
        "select_published_feature_coverage",
        "select_published_feature_freshness",
        "select_published_feature_ranking",
        "select_report_database_summary",
        "select_eligible_listings",
        "validate_feature_rows",
        "FeatureRowKey",
        "SlotWriteCounts",
        "InPlaceSlotChanges",
        "PublicationFinalizationResult",
        "PublicationRecoveryAction",
        "PublicationRecoveryDecision",
        "PublicationSlotSelection",
        "TECH_INDICATORS_WRITER_LOCK_KEY",
        "TECH_INDICATORS_WRITER_LOCK_SEED",
        "TechIndicatorsPayloadSlot",
        "copy_feature_rows_between_slots",
        "fail_unpublished_publication",
        "finalize_publication",
        "inspect_publication_recovery",
        "select_inactive_payload_slots",
        "upsert_feature_rows",
        "FeatureCounts",
        "FeatureRow",
        "ReasonCount",
        "ResolvedBenchmark",
        "SourceBar",
        "TechIndicatorsIssue",
        "TechIndicatorsRunResult",
        "TechIndicatorsScope",
        "TechIndicatorsSummary",
    ]
    assert exceptions_module.__all__ == expected
    assert all(
        getattr(public_api, name) is exception
        for name, exception in zip(expected, PUBLIC_EXCEPTIONS, strict=True)
    )


@pytest.mark.parametrize("exception", PUBLIC_EXCEPTIONS[1:])
def test_specific_exceptions_share_one_package_base(
    exception: type[EmpireStonksTechIndicatorsError],
) -> None:
    failure = exception("safe failure")

    assert isinstance(failure, EmpireStonksTechIndicatorsError)
    assert str(failure) == "safe failure"


def test_cold_public_import_does_not_load_internal_dependencies() -> None:
    code = """
import json
import sys
import empire_stonks_tech_indicators as package

print(json.dumps({
    "exports": package.__all__,
    "internal_modules": sorted(
        name for name in ("numpy", "psycopg", "talib") if name in sys.modules
    ),
}))
"""
    completed = subprocess.run(
        [sys.executable, "-I", "-c", code],
        check=True,
        capture_output=True,
        text=True,
    )

    result = json.loads(completed.stdout)
    assert result["exports"] == list(public_api.__all__)
    assert result["internal_modules"] == []
