import pytest

from empire_stonks_ohlcv import (
    EmpireStonksOHLCVError,
    OHLCVAcquisitionError,
    OHLCVConfigError,
    OHLCVParseError,
    OHLCVPersistenceError,
    OHLCVWorkflowError,
)


def test_public_exception_hierarchy() -> None:
    exception_types = (
        OHLCVAcquisitionError,
        OHLCVConfigError,
        OHLCVParseError,
        OHLCVPersistenceError,
        OHLCVWorkflowError,
    )

    assert all(
        issubclass(error_type, EmpireStonksOHLCVError)
        for error_type in exception_types
    )


def test_workflow_error_rejects_unknown_stage_text() -> None:
    with pytest.raises(ValueError, match="persistence, or reporting"):
        OHLCVWorkflowError("secret provider detail")


def test_workflow_error_accepts_reporting_stage() -> None:
    error = OHLCVWorkflowError("reporting")

    assert error.stage == "reporting"
    assert str(error) == "OHLCV provider workflow failed during reporting."


def test_public_exports_are_explicit() -> None:
    import empire_stonks_ohlcv

    assert empire_stonks_ohlcv.__all__ == [
        "AcquiredObject",
        "AcquireProviderObjects",
        "BoundedIssueSummary",
        "CrossFeedOutcomeCounts",
        "DailyBarDateRange",
        "DailyBarWriteInput",
        "DailyMarketBasketSnapshot",
        "DailyMarketBasketSpec",
        "DAILY_MARKET_BASKETS",
        "DOW30_BASKET",
        "EODDATA_CONTENT_TYPE",
        "EODDATA_DAILY_SOURCE",
        "EODDATA_DAILY_JOB_NAME",
        "EODDATA_DAILY_MARKET_PDF_REPORT_ID",
        "EODDATA_DAILY_PDF_REPORT_ID",
        "EODDATA_PROVIDER_CODE",
        "EODDATA_SYMBOL_LIST_SOURCE",
        "EODDataCredentials",
        "EODDataDailyRunResult",
        "EODDataHTTPResponse",
        "EODDataHTTPTransport",
        "EODDataImportResult",
        "EODDataQuoteListParseResult",
        "EODDataSymbolListParseResult",
        "FeedOutcomeCounts",
        "HighVolumeLowMovementRow",
        "DailyBar",
        "EmpireStonksOHLCVError",
        "ImportIssue",
        "JOB_PROVIDER_CODES",
        "MAX_ISSUE_SAMPLES",
        "MARKET_PDF_REPORT_OBJECT_KIND",
        "MAG7_BASKET",
        "NASDAQ100_BASKET",
        "OHLCVAcquisitionError",
        "OHLCVConfig",
        "OHLCVConfigError",
        "OHLCVParseError",
        "OHLCVPersistenceError",
        "OHLCVWorkflowError",
        "OHLCVRunResult",
        "PDF_REPORT_OBJECT_KIND",
        "ParsedListingBatch",
        "ParsedProviderOutput",
        "ParseProviderObjects",
        "PersistenceCounts",
        "ProviderListing",
        "ProviderListingCoverage",
        "ProviderListingWriteResult",
        "ProviderMarketHealth",
        "ProviderImportResult",
        "ProviderSourceMetadata",
        "ProviderSeriesHealth",
        "ProviderValidationResult",
        "RowRejectionSummary",
        "ProviderWeekdayGapResult",
        "RAW_SOURCE_OBJECT_KIND",
        "REPORT_OBJECT_KIND",
        "REPORT_SCHEMA_VERSION",
        "ResolvedProviderListing",
        "SAFE_FAILURE_MESSAGE",
        "SourceSnapshotRegistration",
        "SourceMarketWriteCounts",
        "STOOQ_DAILY_SOURCE",
        "STOOQ_HISTORY_SOURCE",
        "STOOQ_HISTORY_ARCHIVE_NAME",
        "STOOQ_HISTORY_CORE_ARCHIVE_NAME",
        "STOOQ_HISTORY_HEADER",
        "STOOQ_HISTORY_HEARTBEAT_TIMEOUT_SECONDS",
        "STOOQ_HISTORY_JOB_NAME",
        "STOOQ_HISTORY_MARKETS",
        "STOOQ_HISTORY_PDF_REPORT_FILENAME",
        "STOOQ_HISTORY_PDF_REPORT_ID",
        "STOOQ_HISTORY_PDF_REPORT_LOGICAL_NAME",
        "STOOQ_HISTORY_PROVIDER_CODE",
        "STOOQ_HISTORY_REPORT_FILENAME",
        "STOOQ_HISTORY_REPORT_LOGICAL_NAME",
        "STOOQ_HISTORY_REPORT_TYPE",
        "STOOQ_HISTORY_SUBJECT_KEY",
        "StooqHistoryChunk",
        "StooqHistoryChunkWriteResult",
        "StooqHistoryChunkWriter",
        "StooqHistoryCoverage",
        "StooqHistoryDiscovery",
        "StooqHistoryMarketParseCounts",
        "StooqHistoryMarketCoverage",
        "StooqHistoryMember",
        "StooqHistoryParseProgress",
        "StooqHistoryParser",
        "StooqHistoryParseSummary",
        "StooqHistoryScope",
        "StooqHistoryRunResult",
        "StooqHistorySeriesCoverage",
        "StooqHistoryWriteSummary",
        "YAHOO_DAILY_SOURCE",
        "WeekdayGapCandidate",
        "acquire_eoddata_objects",
        "build_raw_filename",
        "build_raw_object_key",
        "build_eoddata_report",
        "build_eoddata_daily_market_report",
        "build_report_object_key",
        "build_stooq_history_report",
        "eoddata_report_to_json",
        "build_run_summary",
        "execute_import_boundary",
        "import_eoddata_daily",
        "inspect_stooq_history_archive",
        "parse_eoddata_quote_list",
        "parse_eoddata_symbol_list",
        "upsert_provider_listings",
        "upsert_daily_bars",
        "upsert_provider_source_snapshot",
        "select_daily_bar_date_range",
        "select_latest_trading_date",
        "select_provider_latest_trading_date",
        "select_provider_listing_coverage",
        "select_provider_market_health",
        "select_provider_series_health",
        "select_provider_weekday_gaps",
        "select_stooq_history_coverage",
        "run_provider_import",
        "run_provider_pipeline",
        "run_eoddata_daily",
        "run_stooq_history_backfill",
        "render_eoddata_daily_pdf",
        "render_eoddata_daily_market_pdf",
        "render_stooq_history_pdf",
        "store_raw_bytes",
        "stooq_history_report_to_json",
        "store_eoddata_report",
        "store_eoddata_pdf_report",
        "store_eoddata_daily_market_pdf_report",
        "store_raw_file",
        "store_stooq_history_report",
        "store_stooq_history_pdf_report",
    ]
